type MealType = "FRUEHSTUECK" | "MITTAG" | "ABEND" | "SNACK";
type BaseType =
  | "REIS"
  | "NUDELN"
  | "KARTOFFELN"
  | "BROT"
  | "HUELSENFRUECHTE"
  | "HAFER"
  | "BOWL"
  | "SUPPE"
  | "SALAT"
  | "SONSTIGES";

export interface SeedRecipe {
  slug: string;
  title: string;
  description: string;
  mealType: MealType;
  baseType: BaseType;
  servings: number;
  prepMinutes: number;
  tags: string[];
  ingredients: [string, number, string?][];
  steps: string[];
}

function r(
  slug: string,
  title: string,
  description: string,
  mealType: MealType,
  baseType: BaseType,
  servings: number,
  prepMinutes: number,
  tags: string[],
  ingredients: [string, number, string?][],
  steps: string[],
): SeedRecipe {
  return { slug, title, description, mealType, baseType, servings, prepMinutes, tags, ingredients, steps };
}

export const RECIPES: SeedRecipe[] = [
  // ---------- Frühstück ----------
  r("overnight-oats-beeren", "Overnight Oats mit Beeren", "Cremige Haferflocken, über Nacht eingeweicht, mit Beeren und Chia.", "FRUEHSTUECK", "HAFER", 2, 10, ["schnell", "meal-prep", "günstig"],
    [["Haferflocken", 120], ["Sojadrink", 300], ["Sojajoghurt natur", 150], ["Beerenmix (TK)", 150], ["Chiasamen", 20], ["Ahornsirup", 15]],
    ["Haferflocken, Chiasamen, Sojadrink und Joghurt in zwei Gläsern verrühren.", "Mit Ahornsirup süßen und über Nacht in den Kühlschrank stellen.", "Morgens die Beeren darauf geben."]),
  r("erdnuss-bananen-porridge", "Erdnuss-Bananen-Porridge", "Warmer Haferbrei mit Banane und Erdnussmus.", "FRUEHSTUECK", "HAFER", 2, 10, ["schnell", "günstig"],
    [["Haferflocken", 100], ["Sojadrink", 400], ["Banane", 240], ["Erdnussmus", 40], ["Zimt", 2]],
    ["Haferflocken mit Sojadrink aufkochen und 3-4 Minuten köcheln lassen.", "Eine Banane zerdrücken und unterrühren, Zimt dazu.", "Mit der zweiten Banane in Scheiben und Erdnussmus servieren."]),
  r("schoko-protein-porridge", "Schoko-Protein-Porridge", "Proteinreicher Kakao-Porridge für Trainingstage.", "FRUEHSTUECK", "HAFER", 2, 10, ["proteinreich", "schnell"],
    [["Haferflocken", 120], ["Sojadrink", 400], ["Erbsenproteinpulver", 50], ["Kakaopulver", 15], ["Banane", 120], ["Ahornsirup", 10]],
    ["Haferflocken mit Sojadrink aufkochen.", "Vom Herd nehmen, Proteinpulver und Kakao einrühren.", "Mit Bananenscheiben und Ahornsirup servieren."]),
  r("tofu-ruehrei-toast", "Tofu-Rührei auf Vollkornbrot", "Würziges Rührei aus Tofu mit Kurkuma und Hefeflocken.", "FRUEHSTUECK", "BROT", 2, 15, ["proteinreich"],
    [["Tofu natur", 300], ["Zwiebeln", 80], ["Kurkuma", 1], ["Hefeflocken", 15], ["Olivenöl", 10], ["Vollkornbrot", 200], ["Cherrytomaten", 150], ["Salz", 3], ["Pfeffer", 1]],
    ["Zwiebel fein würfeln und in Olivenöl glasig braten.", "Tofu mit den Händen zerbröseln und dazugeben, 5 Minuten braten.", "Kurkuma, Hefeflocken, Salz und Pfeffer unterrühren.", "Auf dem Brot mit halbierten Tomaten servieren."]),
  r("avocado-brot-kichererbsen", "Avocado-Brot mit Kichererbsen", "Zerdrückte Avocado und Kichererbsen auf Vollkornbrot.", "FRUEHSTUECK", "BROT", 2, 10, ["schnell"],
    [["Vollkornbrot", 200], ["Avocado", 150], ["Kichererbsen (Dose)", 130], ["Zitrone", 20], ["Cherrytomaten", 100], ["Chili (frisch)", 5], ["Salz", 2]],
    ["Avocado und Kichererbsen mit einer Gabel grob zerdrücken.", "Mit Zitronensaft und Salz abschmecken.", "Auf das Brot streichen und mit Tomaten und Chili belegen."]),
  r("chia-pudding-mango", "Chia-Pudding mit Mango", "Fruchtiger Chia-Pudding mit Proteinjoghurt und Kokos.", "FRUEHSTUECK", "SONSTIGES", 2, 10, ["meal-prep"],
    [["Chiasamen", 60], ["Sojadrink", 300], ["Soja-Proteinjoghurt", 200], ["Mango", 200], ["Ahornsirup", 15], ["Kokosraspeln", 10]],
    ["Chiasamen mit Sojadrink und Ahornsirup verrühren, mindestens 2 Stunden quellen lassen.", "Joghurt unterheben.", "Mango würfeln und mit Kokosraspeln darauf geben."]),
  r("granola-joghurt-bowl", "Granola-Joghurt-Bowl", "Proteinjoghurt mit Granola, Erdbeeren und Leinsamen.", "FRUEHSTUECK", "BOWL", 2, 5, ["schnell", "proteinreich"],
    [["Soja-Proteinjoghurt", 400], ["Granola", 100], ["Erdbeeren", 200], ["Leinsamen (geschrotet)", 20]],
    ["Joghurt auf zwei Schalen verteilen.", "Erdbeeren schneiden und mit Granola und Leinsamen darüber geben."]),
  r("bananen-pancakes", "Bananen-Pancakes mit Blaubeeren", "Fluffige Pancakes ohne Ei, mit Banane gebunden.", "FRUEHSTUECK", "SONSTIGES", 2, 20, [],
    [["Weizenmehl", 150], ["Sojadrink", 250], ["Banane", 120], ["Backpulver", 8], ["Ahornsirup", 30], ["Rapsöl", 10], ["Blaubeeren", 125]],
    ["Banane zerdrücken, mit Sojadrink verrühren.", "Mehl und Backpulver unterrühren, 5 Minuten ruhen lassen.", "In einer leicht geölten Pfanne kleine Pancakes von beiden Seiten goldbraun backen.", "Mit Blaubeeren und Ahornsirup servieren."]),
  r("bircher-muesli-apfel", "Bircher Müsli mit Apfel", "Klassisches Bircher Müsli mit Walnüssen und Rosinen.", "FRUEHSTUECK", "HAFER", 2, 10, ["meal-prep", "günstig"],
    [["Haferflocken", 100], ["Haferdrink", 250], ["Apfel", 150], ["Walnüsse", 30], ["Sojajoghurt natur", 150], ["Rosinen", 20], ["Zimt", 2]],
    ["Haferflocken mit Haferdrink einweichen, mindestens 30 Minuten oder über Nacht.", "Apfel grob raspeln und mit Joghurt, Rosinen und Zimt unterrühren.", "Mit gehackten Walnüssen servieren."]),
  r("fruehstuecks-burrito", "Frühstücks-Burrito", "Tortilla gefüllt mit Tofu, schwarzen Bohnen und Avocado.", "FRUEHSTUECK", "BROT", 2, 20, ["proteinreich"],
    [["Weizentortilla", 120], ["Tofu natur", 200], ["Schwarze Bohnen (Dose)", 150], ["Paprika rot", 100], ["Avocado", 80], ["Gehackte Tomaten (Dose)", 100], ["Kreuzkümmel", 2], ["Rapsöl", 10]],
    ["Paprika würfeln und im Öl anbraten.", "Tofu zerbröseln, Bohnen, Tomaten und Kreuzkümmel dazugeben und 5 Minuten braten.", "Tortillas erwärmen, füllen, Avocado dazugeben und einrollen."]),
  r("smoothie-bowl-beeren", "Beeren-Smoothie-Bowl", "Dicke Smoothie-Bowl mit Hanfsamen und Haferflocken.", "FRUEHSTUECK", "BOWL", 2, 10, ["schnell"],
    [["Beerenmix (TK)", 300], ["Banane", 240], ["Soja-Proteinjoghurt", 300], ["Haferflocken", 40], ["Hanfsamen (geschält)", 20]],
    ["Gefrorene Beeren, eine Banane und Joghurt cremig mixen.", "In Schalen füllen.", "Mit Bananenscheiben, Haferflocken und Hanfsamen toppen."]),
  r("erdnussbutter-bananen-toast", "Erdnussmus-Bananen-Toast", "Schneller Toast mit Erdnussmus, Banane und Chia.", "FRUEHSTUECK", "BROT", 2, 5, ["schnell", "günstig"],
    [["Vollkorntoast", 112], ["Erdnussmus", 40], ["Banane", 120], ["Chiasamen", 10], ["Zimt", 1]],
    ["Toast rösten.", "Mit Erdnussmus bestreichen, Bananenscheiben darauf legen.", "Mit Chiasamen und Zimt bestreuen."]),
  r("hummus-gemuese-brot", "Hummus-Brot mit Gemüse", "Vollkornbrot mit Hummus, Gurke, Paprika und Kürbiskernen.", "FRUEHSTUECK", "BROT", 2, 10, ["schnell"],
    [["Vollkornbrot", 200], ["Hummus", 100], ["Gurke", 150], ["Paprika rot", 100], ["Kürbiskerne", 20]],
    ["Brot mit Hummus bestreichen.", "Gurke und Paprika in Streifen schneiden und darauf legen.", "Mit Kürbiskernen bestreuen."]),
  r("apfel-zimt-porridge", "Apfel-Zimt-Porridge mit Mandelmus", "Winterlicher Porridge mit gedünstetem Apfel.", "FRUEHSTUECK", "HAFER", 2, 15, [],
    [["Haferflocken", 100], ["Mandeldrink", 400], ["Apfel", 150], ["Mandelmus", 30], ["Zimt", 3], ["Leinsamen (geschrotet)", 15], ["Ahornsirup", 10]],
    ["Apfel würfeln und mit etwas Wasser und Zimt 3 Minuten dünsten.", "Haferflocken mit Mandeldrink aufkochen und quellen lassen.", "Mit Apfel, Mandelmus, Leinsamen und Ahornsirup servieren."]),
  r("kichererbsen-shakshuka", "Kichererbsen-Shakshuka", "Würzige Tomatenpfanne mit Kichererbsen und Tofu, dazu Brötchen.", "FRUEHSTUECK", "HUELSENFRUECHTE", 2, 25, ["proteinreich"],
    [["Kichererbsen (Dose)", 265], ["Passierte Tomaten", 400], ["Paprika rot", 150], ["Zwiebeln", 80], ["Knoblauch", 8], ["Paprikapulver", 5], ["Kreuzkümmel", 2], ["Olivenöl", 15], ["Tofu natur", 150], ["Petersilie", 10], ["Brötchen", 120]],
    ["Zwiebel, Knoblauch und Paprika im Öl anbraten.", "Gewürze kurz mitrösten, Tomaten und Kichererbsen dazugeben, 10 Minuten köcheln.", "Tofu in Würfeln darauf verteilen und 5 Minuten ziehen lassen.", "Mit Petersilie bestreuen und mit Brötchen servieren."]),
  r("muesli-proteinjoghurt", "Müsli mit Proteinjoghurt", "Der schnellste Start in den Tag.", "FRUEHSTUECK", "HAFER", 2, 3, ["schnell"],
    [["Müsli", 120], ["Soja-Proteinjoghurt", 300], ["Banane", 120], ["Sojadrink", 200]],
    ["Müsli in Schalen geben.", "Mit Joghurt und Sojadrink übergießen.", "Banane darüber schneiden."]),

  // ---------- Reis ----------
  r("linsen-dal-reis", "Rotes Linsen-Dal mit Reis", "Cremiges Dal mit Kokos, Spinat und Basmatireis.", "MITTAG", "REIS", 2, 30, ["proteinreich", "günstig", "meal-prep"],
    [["Rote Linsen", 160], ["Basmatireis", 140], ["Kokosmilch", 100], ["Passierte Tomaten", 200], ["Zwiebeln", 80], ["Knoblauch", 8], ["Ingwer", 10], ["Currypulver", 8], ["Kurkuma", 2], ["Blattspinat (TK)", 150], ["Rapsöl", 10]],
    ["Reis nach Packungsanweisung kochen.", "Zwiebel, Knoblauch und Ingwer im Öl anschwitzen, Gewürze kurz mitrösten.", "Linsen, Tomaten, Kokosmilch und 400 ml Wasser dazugeben, 15 Minuten köcheln.", "Spinat unterrühren und mit Reis servieren."]),
  r("teriyaki-tofu-reis", "Teriyaki-Tofu mit Brokkoli", "Knuspriger Tofu in Teriyaki-Sauce mit Reis und Brokkoli.", "ABEND", "REIS", 2, 30, ["proteinreich"],
    [["Tofu natur", 400], ["Basmatireis", 150], ["Brokkoli", 300], ["Sojasauce", 40], ["Ahornsirup", 20], ["Ingwer", 10], ["Knoblauch", 8], ["Sesam", 10], ["Sesamöl (geröstet)", 10]],
    ["Reis kochen, Brokkoli in Röschen dämpfen.", "Tofu würfeln und im Sesamöl rundum knusprig braten.", "Sojasauce, Ahornsirup, geriebenen Ingwer und Knoblauch verrühren, in die Pfanne geben und einkochen lassen.", "Alles anrichten und mit Sesam bestreuen."]),
  r("chili-sin-carne", "Chili sin Carne mit Reis", "Deftiges Chili mit Sojaschnetzeln, Bohnen und Mais.", "ABEND", "REIS", 2, 35, ["proteinreich", "meal-prep", "günstig"],
    [["Sojaschnetzel", 80], ["Kidneybohnen (Dose)", 250], ["Mais (Dose)", 140], ["Gehackte Tomaten (Dose)", 400], ["Tomatenmark", 30], ["Paprika rot", 150], ["Zwiebeln", 80], ["Knoblauch", 8], ["Kreuzkümmel", 3], ["Paprikapulver", 5], ["Olivenöl", 10], ["Vollkornreis", 140]],
    ["Sojaschnetzel 10 Minuten in heißer Brühe oder Wasser einweichen, ausdrücken.", "Zwiebel, Knoblauch und Schnetzel im Öl kräftig anbraten, Tomatenmark und Gewürze mitrösten.", "Paprika, Tomaten, Bohnen und Mais dazugeben und 20 Minuten köcheln.", "Mit Vollkornreis servieren."]),
  r("kichererbsen-kokos-curry", "Kichererbsen-Kokos-Curry", "Rotes Curry mit Gemüse und Jasminreis.", "MITTAG", "REIS", 2, 30, [],
    [["Kichererbsen (Dose)", 265], ["Kokosmilch", 200], ["Currypaste (rot)", 30], ["Zucchini", 200], ["Paprika rot", 150], ["Karotten", 100], ["Jasminreis", 140], ["Limette", 30], ["Koriander", 10]],
    ["Reis kochen.", "Currypaste in einem Topf kurz anrösten, Kokosmilch angießen.", "Gemüse in Stücken und Kichererbsen dazugeben, 12 Minuten köcheln.", "Mit Limettensaft abschmecken und mit Koriander servieren."]),
  r("gebratener-reis-edamame", "Gebratener Reis mit Edamame", "Schneller Wok-Reis mit Räuchertofu und Gemüse.", "ABEND", "REIS", 2, 25, ["proteinreich", "schnell"],
    [["Jasminreis", 140], ["Edamame (TK)", 200], ["Erbsen (TK)", 100], ["Karotten", 100], ["Frühlingszwiebeln", 40], ["Räuchertofu", 200], ["Sojasauce", 30], ["Sesamöl (geröstet)", 10], ["Knoblauch", 8]],
    ["Reis kochen und abkühlen lassen (am besten vom Vortag).", "Räuchertofu würfeln und im Sesamöl anbraten.", "Karotten, Knoblauch, Edamame und Erbsen dazugeben, 4 Minuten braten.", "Reis und Sojasauce dazugeben, alles kräftig durchbraten, mit Frühlingszwiebeln servieren."]),
  r("pilz-risotto-bohnen", "Pilzrisotto mit weißen Bohnen", "Cremiges Risotto ohne Sahne, mit Hefeflocken.", "ABEND", "REIS", 2, 35, [],
    [["Risottoreis", 160], ["Champignons", 300], ["Zwiebeln", 80], ["Gemüsebrühe", 10], ["Hefeflocken", 15], ["Olivenöl", 15], ["Erbsen (TK)", 150], ["Weiße Bohnen (Dose)", 250], ["Knoblauch", 6], ["Petersilie", 10]],
    ["Zwiebel und Knoblauch im Öl anschwitzen, Reis dazugeben und glasig rühren.", "Nach und nach 800 ml Brühe angießen und unter Rühren 18 Minuten garen.", "Pilze separat scharf anbraten.", "Pilze, Erbsen, Bohnen und Hefeflocken unterheben, mit Petersilie servieren."]),
  r("suesskartoffel-erdnuss-curry", "Süßkartoffel-Erdnuss-Curry", "Afrikanisch inspiriertes Curry mit Erdnuss und Spinat.", "MITTAG", "REIS", 2, 35, ["meal-prep"],
    [["Basmatireis", 140], ["Süßkartoffeln", 400], ["Kichererbsen (Dose)", 265], ["Erdnussmus", 40], ["Passierte Tomaten", 200], ["Blattspinat (TK)", 150], ["Currypulver", 6], ["Ingwer", 10]],
    ["Reis kochen.", "Süßkartoffeln würfeln und mit Ingwer, Curry, Tomaten und 300 ml Wasser 15 Minuten köcheln.", "Erdnussmus, Kichererbsen und Spinat unterrühren und 5 Minuten ziehen lassen."]),
  r("jambalaya-vegan", "Vegane Jambalaya", "Würziger Reistopf aus den Südstaaten mit Hack und Bohnen.", "ABEND", "REIS", 2, 40, ["proteinreich", "meal-prep"],
    [["Vollkornreis", 150], ["Kidneybohnen (Dose)", 250], ["Paprika rot", 200], ["Staudensellerie", 100], ["Zwiebeln", 80], ["Passierte Tomaten", 300], ["Paprikapulver", 6], ["Veganes Hack", 200], ["Olivenöl", 10], ["Gemüsebrühe", 8]],
    ["Hack im Öl krümelig braten, Zwiebel, Sellerie und Paprika dazugeben.", "Reis und Paprikapulver unterrühren, Tomaten und 400 ml Brühe angießen.", "Zugedeckt 30 Minuten garen, Bohnen die letzten 5 Minuten mitziehen lassen."]),
  r("seitan-gemuesepfanne", "Seitan-Gemüsepfanne mit Reis", "Proteinbombe aus dem Wok.", "MITTAG", "REIS", 2, 25, ["proteinreich", "schnell"],
    [["Seitan", 250], ["Brokkoli", 200], ["Paprika rot", 150], ["Karotten", 100], ["Sojasauce", 30], ["Ingwer", 10], ["Rapsöl", 15], ["Basmatireis", 120]],
    ["Reis kochen.", "Seitan in Streifen schneiden und im Öl scharf anbraten.", "Gemüse dazugeben und bissfest braten.", "Mit Sojasauce und Ingwer ablöschen und mit Reis servieren."]),
  r("gefuellte-paprika", "Gefüllte Paprika", "Paprika gefüllt mit Reis und veganem Hack, überbacken.", "ABEND", "REIS", 2, 50, ["proteinreich"],
    [["Paprika rot", 600], ["Vollkornreis", 100], ["Veganes Hack", 200], ["Passierte Tomaten", 300], ["Zwiebeln", 80], ["Veganer Reibekäse", 40]],
    ["Reis vorkochen. Ofen auf 190 Grad vorheizen.", "Hack mit Zwiebel anbraten und mit dem Reis mischen.", "Paprika aushöhlen, füllen und in eine Form mit den Tomaten setzen.", "Mit Reibekäse bestreuen und 30 Minuten backen."]),

  // ---------- Nudeln ----------
  r("linsen-bolognese", "Spaghetti mit Linsen-Bolognese", "Klassiker mit roten Linsen statt Hack.", "ABEND", "NUDELN", 2, 30, ["proteinreich", "günstig", "meal-prep"],
    [["Spaghetti", 200], ["Rote Linsen", 100], ["Passierte Tomaten", 500], ["Karotten", 100], ["Zwiebeln", 80], ["Knoblauch", 8], ["Tomatenmark", 30], ["Olivenöl", 10], ["Hefeflocken", 10]],
    ["Zwiebel, Knoblauch und fein geriebene Karotte im Öl anbraten, Tomatenmark mitrösten.", "Linsen, Tomaten und 200 ml Wasser dazugeben, 15 Minuten köcheln.", "Spaghetti kochen.", "Mit Hefeflocken bestreut servieren."]),
  r("brokkoli-cashew-pasta", "Pasta mit Brokkoli-Cashew-Sauce", "Cremige Sauce aus Cashews, dazu Räuchertofu.", "MITTAG", "NUDELN", 2, 25, ["proteinreich"],
    [["Penne", 200], ["Brokkoli", 300], ["Cashewkerne", 50], ["Hefeflocken", 15], ["Knoblauch", 6], ["Zitrone", 20], ["Sojadrink", 150], ["Räuchertofu", 150]],
    ["Pasta kochen, Brokkoli die letzten 4 Minuten mitgaren.", "Cashews, Hefeflocken, Knoblauch, Zitronensaft und Sojadrink fein pürieren.", "Räuchertofu würfeln und anbraten.", "Alles mit der Sauce vermengen."]),
  r("pesto-pasta-bohnen", "Pesto-Pasta mit Bohnen und Tomaten", "Schnell, frisch und sättigend.", "MITTAG", "NUDELN", 2, 15, ["schnell"],
    [["Spaghetti", 200], ["Pesto (vegan)", 60], ["Cherrytomaten", 200], ["Rucola", 40], ["Weiße Bohnen (Dose)", 250]],
    ["Pasta kochen, die Bohnen in der letzten Minute mit ins Wasser geben.", "Abgießen und mit Pesto vermengen.", "Mit halbierten Tomaten und Rucola servieren."]),
  r("linsennudeln-spinat", "Linsennudeln mit Spinat-Tomaten-Sauce", "Proteinreiche Pasta aus roten Linsen.", "ABEND", "NUDELN", 2, 20, ["proteinreich", "schnell"],
    [["Linsennudeln", 200], ["Blattspinat (TK)", 300], ["Passierte Tomaten", 300], ["Knoblauch", 8], ["Sojacreme", 100], ["Zwiebeln", 80]],
    ["Linsennudeln nach Packungsanweisung kochen.", "Zwiebel und Knoblauch anschwitzen, Spinat und Tomaten dazugeben und 8 Minuten köcheln.", "Sojacreme einrühren und mit den Nudeln mischen."]),
  r("pad-thai-tofu", "Pad Thai mit Tofu", "Reisnudeln mit Tofu, Erdnüssen und Limette.", "ABEND", "NUDELN", 2, 25, [],
    [["Reisnudeln", 160], ["Tofu natur", 250], ["Karotten", 100], ["Frühlingszwiebeln", 40], ["Erdnüsse", 30], ["Limette", 30], ["Sojasauce", 30], ["Ahornsirup", 15], ["Knoblauch", 6], ["Rapsöl", 10]],
    ["Reisnudeln in heißem Wasser einweichen.", "Tofu würfeln und im Öl knusprig braten, Karotte in Streifen und Knoblauch dazu.", "Nudeln, Sojasauce, Ahornsirup und Limettensaft dazugeben und durchschwenken.", "Mit gehackten Erdnüssen und Frühlingszwiebeln servieren."]),
  r("mac-and-cheese-vegan", "Veganes Mac and Cheese", "Käsige Sauce aus Kartoffel, Karotte und Cashews.", "MITTAG", "NUDELN", 2, 30, [],
    [["Penne", 200], ["Kartoffeln", 150], ["Karotten", 100], ["Cashewkerne", 40], ["Hefeflocken", 20], ["Senf", 10], ["Sojadrink", 200], ["Erbsen (TK)", 150]],
    ["Kartoffel und Karotte würfeln und 12 Minuten weich kochen.", "Mit Cashews, Hefeflocken, Senf und Sojadrink cremig pürieren.", "Pasta kochen, Erbsen kurz mitgaren.", "Mit der Sauce vermengen."]),
  r("one-pot-pasta-gemuese", "One-Pot-Pasta mit Gemüse", "Alles in einem Topf, wenig Abwasch.", "ABEND", "NUDELN", 2, 25, ["meal-prep"],
    [["Vollkornnudeln", 200], ["Zucchini", 200], ["Paprika rot", 150], ["Gehackte Tomaten (Dose)", 400], ["Zwiebeln", 80], ["Knoblauch", 8], ["Gemüsebrühe", 8], ["Olivenöl", 10], ["Kichererbsen (Dose)", 265], ["Veganer Reibekäse", 30]],
    ["Alle Zutaten außer Reibekäse mit 500 ml Wasser in einen großen Topf geben.", "Aufkochen und unter gelegentlichem Rühren 12 Minuten köcheln, bis die Pasta gar ist.", "Mit Reibekäse servieren."]),
  r("linsen-lasagne", "Linsen-Lasagne", "Lasagne mit Linsen-Ragout und heller Sauce.", "ABEND", "NUDELN", 4, 70, ["meal-prep"],
    [["Lasagneplatten", 250], ["Rote Linsen", 120], ["Passierte Tomaten", 500], ["Zucchini", 200], ["Sojadrink", 400], ["Weizenmehl", 30], ["Pflanzenmargarine", 30], ["Veganer Reibekäse", 60], ["Zwiebeln", 80]],
    ["Zwiebel und Zucchini anbraten, Linsen und Tomaten dazugeben und 15 Minuten köcheln.", "Margarine schmelzen, Mehl einrühren, mit Sojadrink ablöschen und zu einer Sauce kochen.", "Abwechselnd Ragout, Platten und Sauce schichten, mit Reibekäse abschließen.", "Bei 180 Grad 35 Minuten backen."]),
  r("aglio-olio-bohnen", "Spaghetti Aglio e Olio mit Bohnen", "Knoblauch, Chili und weiße Bohnen für mehr Protein.", "MITTAG", "NUDELN", 2, 15, ["schnell", "günstig"],
    [["Spaghetti", 200], ["Olivenöl", 25], ["Knoblauch", 15], ["Chili (frisch)", 5], ["Petersilie", 15], ["Weiße Bohnen (Dose)", 250], ["Zitrone", 20], ["Hefeflocken", 10]],
    ["Spaghetti kochen.", "Knoblauch in Scheiben und Chili im Öl sanft goldgelb braten.", "Bohnen dazugeben und erwärmen.", "Pasta mit etwas Kochwasser, Petersilie, Zitrone und Hefeflocken durchschwenken."]),
  r("nudelsalat-kichererbsen", "Nudelsalat mit Kichererbsen", "Frischer Nudelsalat mit Joghurtdressing.", "MITTAG", "NUDELN", 2, 20, ["meal-prep"],
    [["Vollkornnudeln", 180], ["Kichererbsen (Dose)", 265], ["Paprika rot", 150], ["Gurke", 150], ["Mais (Dose)", 140], ["Soja-Proteinjoghurt", 150], ["Senf", 10], ["Apfelessig", 15], ["Frühlingszwiebeln", 30]],
    ["Nudeln kochen und abschrecken.", "Gemüse würfeln.", "Joghurt, Senf und Essig zu einem Dressing verrühren.", "Alles mischen und 15 Minuten durchziehen lassen."]),

  // ---------- Kartoffeln ----------
  r("ofenkartoffeln-hummus", "Ofenkartoffeln mit Hummus und Gemüse", "Blech-Gericht mit Kichererbsen und Hummus.", "ABEND", "KARTOFFELN", 2, 45, ["günstig"],
    [["Kartoffeln", 700], ["Brokkoli", 200], ["Paprika rot", 150], ["Kichererbsen (Dose)", 265], ["Olivenöl", 15], ["Paprikapulver", 5], ["Hummus", 100]],
    ["Ofen auf 210 Grad vorheizen.", "Kartoffeln vierteln, mit Öl und Paprikapulver mischen und 20 Minuten backen.", "Brokkoli, Paprika und Kichererbsen dazugeben und weitere 15 Minuten backen.", "Mit Hummus servieren."]),
  r("kartoffel-blumenkohl-curry", "Kartoffel-Blumenkohl-Curry", "Aloo Gobi mit Erbsen und Kichererbsen.", "MITTAG", "KARTOFFELN", 2, 35, ["günstig", "meal-prep"],
    [["Kartoffeln", 500], ["Blumenkohl", 400], ["Erbsen (TK)", 150], ["Passierte Tomaten", 300], ["Kokosmilch", 100], ["Currypulver", 8], ["Zwiebeln", 80], ["Ingwer", 10], ["Kichererbsen (Dose)", 265]],
    ["Zwiebel und Ingwer anschwitzen, Curry mitrösten.", "Kartoffelwürfel, Tomaten, Kokosmilch und 200 ml Wasser dazugeben, 10 Minuten köcheln.", "Blumenkohl und Kichererbsen dazugeben und 12 Minuten weiter garen, Erbsen zum Schluss."]),
  r("suesskartoffel-tempeh", "Süßkartoffel mit Tempeh und Grünkohl", "Geröstete Süßkartoffel, knuspriges Tempeh, Tahini-Dressing.", "ABEND", "KARTOFFELN", 2, 40, ["proteinreich"],
    [["Süßkartoffeln", 500], ["Tempeh", 200], ["Grünkohl", 150], ["Tahini", 30], ["Zitrone", 20], ["Olivenöl", 10], ["Kürbiskerne", 20], ["Sojasauce", 15]],
    ["Süßkartoffeln würfeln und bei 200 Grad 30 Minuten rösten.", "Tempeh in Scheiben schneiden, mit Sojasauce marinieren und knusprig braten.", "Grünkohl kurz in der Pfanne zusammenfallen lassen.", "Tahini mit Zitronensaft und Wasser verrühren und über alles geben."]),
  r("bratkartoffeln-raeuchertofu", "Bratkartoffeln mit Räuchertofu und Bohnen", "Deftige Hausmannskost, vegan.", "ABEND", "KARTOFFELN", 2, 35, ["proteinreich"],
    [["Kartoffeln", 600], ["Räuchertofu", 200], ["Zwiebeln", 100], ["Rapsöl", 15], ["Grüne Bohnen (TK)", 300], ["Paprikapulver", 3]],
    ["Kartoffeln in der Schale vorkochen, pellen und in Scheiben schneiden.", "Im Öl goldbraun braten, Zwiebeln und Räuchertofu dazugeben.", "Bohnen in Salzwasser garen.", "Mit Paprikapulver würzen und servieren."]),
  r("linsen-shepherds-pie", "Linsen-Shepherd's-Pie", "Belugalinsen-Ragout unter Kartoffelpüree.", "ABEND", "KARTOFFELN", 3, 60, ["meal-prep"],
    [["Kartoffeln", 800], ["Belugalinsen", 150], ["Karotten", 150], ["Erbsen (TK)", 100], ["Zwiebeln", 80], ["Tomatenmark", 30], ["Gemüsebrühe", 8], ["Sojadrink", 100], ["Pflanzenmargarine", 20]],
    ["Linsen in Brühe 20 Minuten garen.", "Zwiebel und Karotten anbraten, Tomatenmark, Linsen und Erbsen dazugeben.", "Kartoffeln kochen und mit Sojadrink und Margarine zu Püree stampfen.", "Ragout in eine Form, Püree darauf, bei 200 Grad 20 Minuten backen."]),
  r("gefuellte-suesskartoffel", "Gefüllte Süßkartoffel mexikanisch", "Mit schwarzen Bohnen, Mais und Avocado.", "MITTAG", "KARTOFFELN", 2, 45, [],
    [["Süßkartoffeln", 600], ["Schwarze Bohnen (Dose)", 250], ["Mais (Dose)", 140], ["Avocado", 100], ["Limette", 30], ["Soja-Proteinjoghurt", 100], ["Kreuzkümmel", 2]],
    ["Süßkartoffeln einstechen und bei 200 Grad 40 Minuten backen.", "Bohnen und Mais mit Kreuzkümmel erwärmen.", "Kartoffeln aufschneiden, füllen und mit Avocado, Limette und Joghurt toppen."]),
  r("gnocchi-tomate-spinat", "Gnocchi-Pfanne mit Spinat und Tomaten", "Knusprige Gnocchi in cremiger Tomatensauce.", "ABEND", "KARTOFFELN", 2, 20, ["schnell"],
    [["Gnocchi", 500], ["Blattspinat (TK)", 200], ["Cherrytomaten", 200], ["Sojacreme", 100], ["Knoblauch", 6], ["Weiße Bohnen (Dose)", 250], ["Olivenöl", 10]],
    ["Gnocchi im Öl goldbraun anbraten.", "Knoblauch, Tomaten und Spinat dazugeben und 5 Minuten garen.", "Bohnen und Sojacreme unterrühren und kurz aufkochen."]),
  r("tofu-gulasch-kartoffeln", "Tofu-Gulasch mit Kartoffeln", "Paprikagulasch mit Tofu, dazu Salzkartoffeln.", "ABEND", "KARTOFFELN", 2, 45, ["proteinreich", "meal-prep"],
    [["Tofu natur", 400], ["Paprika rot", 300], ["Zwiebeln", 150], ["Tomatenmark", 40], ["Paprikapulver", 10], ["Gemüsebrühe", 8], ["Rapsöl", 15], ["Kartoffeln", 600]],
    ["Tofu zerbröseln oder würfeln und im Öl kräftig anbraten.", "Zwiebeln und Paprika dazugeben, Tomatenmark und Paprikapulver mitrösten.", "Mit 400 ml Brühe ablöschen und 25 Minuten schmoren.", "Kartoffeln kochen und dazu servieren."]),
  r("kartoffelsalat-raeuchertofu", "Kartoffelsalat mit Räuchertofu", "Schwäbischer Kartoffelsalat mit Brühe und Gurke.", "MITTAG", "KARTOFFELN", 2, 40, ["meal-prep", "günstig"],
    [["Kartoffeln", 800], ["Gurke", 150], ["Zwiebeln", 60], ["Senf", 15], ["Apfelessig", 20], ["Rapsöl", 20], ["Gemüsebrühe", 5], ["Räuchertofu", 200]],
    ["Kartoffeln kochen, pellen und warm in Scheiben schneiden.", "Brühe mit Zwiebel, Essig, Senf und Öl aufkochen und über die Kartoffeln gießen.", "Gurke hobeln und unterheben, 30 Minuten ziehen lassen.", "Mit gebratenem Räuchertofu servieren."]),

  // ---------- Hülsenfrüchte ----------
  r("kichererbsen-spinat-curry", "Kichererbsen-Spinat-Curry mit Pita", "Chana Masala mit viel Spinat.", "ABEND", "HUELSENFRUECHTE", 2, 30, ["proteinreich", "günstig"],
    [["Kichererbsen (Dose)", 530], ["Blattspinat (TK)", 300], ["Gehackte Tomaten (Dose)", 400], ["Zwiebeln", 80], ["Knoblauch", 8], ["Ingwer", 10], ["Currypulver", 8], ["Kokosmilch", 100], ["Pita-Brot", 160]],
    ["Zwiebel, Knoblauch und Ingwer anbraten, Curry mitrösten.", "Tomaten, Kichererbsen und Kokosmilch dazugeben, 15 Minuten köcheln.", "Spinat unterrühren, bis er zusammenfällt.", "Mit warmem Pita servieren."]),
  r("falafel-teller", "Falafel-Teller mit Tahini", "Selbstgemachte Falafel mit Salat und Pita.", "MITTAG", "HUELSENFRUECHTE", 3, 50, [],
    [["Kichererbsen (trocken)", 200], ["Zwiebeln", 60], ["Petersilie", 20], ["Knoblauch", 6], ["Kreuzkümmel", 4], ["Weizenmehl", 20], ["Rapsöl", 30], ["Tahini", 30], ["Pita-Brot", 160], ["Gurke", 150], ["Tomaten", 150]],
    ["Kichererbsen über Nacht einweichen und abtropfen lassen.", "Mit Zwiebel, Knoblauch, Petersilie, Kreuzkümmel und Mehl grob mixen.", "Bällchen formen und in wenig Öl von allen Seiten braten.", "Mit Tahini-Sauce, Gurke, Tomate und Pita servieren."]),
  r("bohnen-ragout-polenta", "Weißes Bohnen-Ragout mit Polenta", "Mediterranes Ragout auf cremiger Polenta.", "ABEND", "HUELSENFRUECHTE", 2, 30, [],
    [["Weiße Bohnen (Dose)", 500], ["Polenta", 150], ["Gehackte Tomaten (Dose)", 400], ["Zucchini", 200], ["Knoblauch", 8], ["Olivenöl", 15], ["Rucola", 40], ["Hefeflocken", 10]],
    ["Polenta in 600 ml Salzwasser einrühren und 10 Minuten quellen lassen, Hefeflocken unterrühren.", "Knoblauch und Zucchini im Öl anbraten, Tomaten und Bohnen dazugeben, 10 Minuten köcheln.", "Ragout auf der Polenta anrichten, mit Rucola toppen."]),
  r("belugalinsen-salat", "Belugalinsen-Salat mit Räuchertofu", "Herzhafter Linsensalat mit Walnüssen.", "MITTAG", "SALAT", 2, 30, ["proteinreich", "meal-prep"],
    [["Belugalinsen", 150], ["Rucola", 60], ["Cherrytomaten", 200], ["Gurke", 150], ["Walnüsse", 30], ["Balsamico", 20], ["Olivenöl", 15], ["Senf", 5], ["Ahornsirup", 10], ["Räuchertofu", 150]],
    ["Linsen 20 Minuten in Salzwasser garen und abkühlen lassen.", "Tomaten, Gurke und Räuchertofu würfeln.", "Dressing aus Balsamico, Öl, Senf und Ahornsirup rühren.", "Alles mit Rucola und Walnüssen mischen."]),

  // ---------- Brot / Wraps ----------
  r("gyros-pita-sojaschnetzel", "Gyros-Pita mit Soja-Tzatziki", "Knusprige Sojaschnetzel mit Gyros-Würzung.", "ABEND", "BROT", 2, 30, ["proteinreich"],
    [["Sojaschnetzel", 120], ["Pita-Brot", 160], ["Soja-Proteinjoghurt", 150], ["Gurke", 150], ["Knoblauch", 6], ["Zwiebeln", 60], ["Tomaten", 150], ["Paprikapulver", 5], ["Olivenöl", 15], ["Gemüsebrühe", 8]],
    ["Sojaschnetzel in heißer Brühe 10 Minuten einweichen und gut ausdrücken.", "Mit Paprikapulver im Öl knusprig braten.", "Joghurt mit geriebener Gurke und Knoblauch zu Tzatziki verrühren.", "Pita füllen mit Schnetzeln, Tomate, Zwiebel und Tzatziki."]),
  r("bohnen-burger", "Kidneybohnen-Burger", "Saftige Bohnen-Patties im Brötchen.", "ABEND", "BROT", 2, 35, ["günstig"],
    [["Kidneybohnen (Dose)", 250], ["Haferflocken", 60], ["Zwiebeln", 60], ["Tomatenmark", 20], ["Paprikapulver", 3], ["Brötchen", 240], ["Römersalat", 60], ["Tomaten", 150], ["Tomatenketchup", 30], ["Rapsöl", 15]],
    ["Bohnen zerdrücken und mit Haferflocken, fein gewürfelter Zwiebel, Tomatenmark und Paprika mischen.", "Vier Patties formen und 10 Minuten ruhen lassen.", "Im Öl von beiden Seiten 4 Minuten braten.", "Brötchen mit Salat, Tomate, Patty und Ketchup belegen."]),
  r("tacos-veganes-hack", "Tacos mit veganem Hack", "Weiche Tortillas mit würzigem Hack und Guacamole.", "ABEND", "BROT", 2, 25, ["proteinreich", "schnell"],
    [["Weizentortilla", 240], ["Veganes Hack", 200], ["Mais (Dose)", 140], ["Römersalat", 80], ["Tomaten", 150], ["Avocado", 100], ["Kreuzkümmel", 2], ["Paprikapulver", 4], ["Limette", 20]],
    ["Hack mit Kreuzkümmel und Paprikapulver krümelig braten, Mais dazugeben.", "Avocado mit Limettensaft zerdrücken.", "Tortillas erwärmen und mit Hack, Salat, Tomaten und Guacamole füllen."]),

  // ---------- Bowls ----------
  r("buddha-bowl-quinoa", "Buddha Bowl mit Quinoa", "Bunte Bowl mit Süßkartoffel, Kichererbsen und Tahini.", "MITTAG", "BOWL", 2, 35, [],
    [["Quinoa", 140], ["Kichererbsen (Dose)", 265], ["Süßkartoffeln", 300], ["Rotkohl", 100], ["Avocado", 100], ["Tahini", 30], ["Zitrone", 20], ["Spinat (frisch)", 60]],
    ["Quinoa kochen.", "Süßkartoffel würfeln und mit den Kichererbsen bei 200 Grad 25 Minuten rösten.", "Rotkohl fein hobeln.", "Alles mit Spinat und Avocado anrichten, Tahini-Zitronen-Dressing darüber."]),
  r("tempeh-erdnuss-bowl", "Tempeh-Erdnuss-Bowl", "Vollkornreis, Tempeh, Edamame und Erdnuss-Sauce.", "ABEND", "BOWL", 2, 30, ["proteinreich"],
    [["Vollkornreis", 140], ["Tempeh", 200], ["Brokkoli", 200], ["Edamame (TK)", 100], ["Karotten", 100], ["Erdnussmus", 30], ["Sojasauce", 20], ["Limette", 20]],
    ["Reis kochen, Brokkoli und Edamame dämpfen.", "Tempeh würfeln und knusprig braten.", "Erdnussmus mit Sojasauce, Limettensaft und etwas Wasser verrühren.", "Alles in Schalen anrichten, Karotten raspeln, Sauce darüber."]),
  r("couscous-bowl", "Mediterrane Couscous-Bowl", "Couscous mit geröstetem Gemüse und Hummus.", "MITTAG", "BOWL", 2, 25, ["schnell"],
    [["Couscous", 140], ["Kichererbsen (Dose)", 265], ["Zucchini", 200], ["Paprika rot", 150], ["Hummus", 80], ["Cherrytomaten", 150], ["Olivenöl", 10]],
    ["Couscous mit kochendem Wasser übergießen und 5 Minuten quellen lassen.", "Zucchini, Paprika und Kichererbsen im Öl anbraten.", "Mit Tomaten und Hummus anrichten."]),
  r("sushi-bowl-tofu", "Sushi-Bowl mit Tofu", "Alle Aromen von Sushi, ohne Rollen.", "MITTAG", "BOWL", 2, 25, [],
    [["Jasminreis", 140], ["Edamame (TK)", 150], ["Gurke", 150], ["Avocado", 100], ["Karotten", 100], ["Sojasauce", 25], ["Sesam", 10], ["Apfelessig", 15], ["Tofu natur", 200]],
    ["Reis kochen und mit Essig würzen.", "Tofu würfeln und mit etwas Sojasauce anbraten.", "Gemüse in Streifen schneiden, Edamame garen.", "Alles auf dem Reis anrichten, mit Sesam und Sojasauce servieren."]),
  r("burrito-bowl", "Burrito Bowl", "Reis, Bohnen, Mais, Räuchertofu und Avocado.", "ABEND", "BOWL", 2, 25, ["proteinreich", "meal-prep"],
    [["Vollkornreis", 140], ["Schwarze Bohnen (Dose)", 250], ["Mais (Dose)", 140], ["Avocado", 150], ["Cherrytomaten", 150], ["Limette", 30], ["Rotkohl", 100], ["Kreuzkümmel", 2], ["Paprikapulver", 3], ["Räuchertofu", 200]],
    ["Reis kochen.", "Räuchertofu würfeln und mit den Gewürzen anbraten.", "Bohnen und Mais erwärmen.", "Alles in Schalen anrichten, mit Avocado, Tomaten, Rotkohl und Limette toppen."]),

  // ---------- Suppen ----------
  r("rote-linsen-suppe", "Rote-Linsen-Suppe", "Türkisch inspirierte Suppe mit Kreuzkümmel und Zitrone.", "MITTAG", "SUPPE", 2, 30, ["günstig", "proteinreich", "meal-prep"],
    [["Rote Linsen", 200], ["Karotten", 200], ["Zwiebeln", 80], ["Kokosmilch", 100], ["Passierte Tomaten", 200], ["Gemüsebrühe", 10], ["Kreuzkümmel", 3], ["Zitrone", 20], ["Vollkornbrot", 100]],
    ["Zwiebel und Karotten anschwitzen, Kreuzkümmel mitrösten.", "Linsen, Tomaten und 800 ml Brühe dazugeben und 20 Minuten köcheln.", "Kokosmilch dazu, fein pürieren und mit Zitrone abschmecken.", "Mit Brot servieren."]),
  r("kuerbissuppe-ingwer", "Kürbissuppe mit Ingwer", "Samtige Hokkaido-Suppe mit gerösteten Kürbiskernen.", "ABEND", "SUPPE", 2, 35, [],
    [["Kürbis (Hokkaido)", 800], ["Kartoffeln", 200], ["Zwiebeln", 80], ["Ingwer", 15], ["Kokosmilch", 150], ["Gemüsebrühe", 10], ["Kürbiskerne", 30], ["Brötchen", 120]],
    ["Kürbis mit Schale würfeln, Kartoffel und Zwiebel ebenso.", "Mit Ingwer anschwitzen, 700 ml Brühe angießen und 20 Minuten köcheln.", "Kokosmilch dazu und fein pürieren.", "Kürbiskerne ohne Fett rösten und darüber streuen, dazu Brötchen."]),
  r("minestrone-bohnen", "Minestrone mit weißen Bohnen", "Italienische Gemüsesuppe mit Nudeln.", "MITTAG", "SUPPE", 2, 35, ["günstig", "meal-prep"],
    [["Weiße Bohnen (Dose)", 250], ["Vollkornnudeln", 80], ["Karotten", 150], ["Zucchini", 150], ["Staudensellerie", 100], ["Gehackte Tomaten (Dose)", 400], ["Gemüsebrühe", 10], ["Olivenöl", 10], ["Vollkornbrot", 100]],
    ["Gemüse klein würfeln und im Öl anschwitzen.", "Tomaten und 800 ml Brühe dazugeben, 15 Minuten köcheln.", "Nudeln und Bohnen dazugeben und weitere 10 Minuten garen.", "Mit Brot servieren."]),
  r("linsen-eintopf", "Linseneintopf mit Räuchertofu", "Deftiger Eintopf wie bei Oma, nur vegan.", "ABEND", "SUPPE", 2, 45, ["proteinreich", "meal-prep"],
    [["Belugalinsen", 180], ["Kartoffeln", 300], ["Karotten", 150], ["Lauch", 150], ["Staudensellerie", 100], ["Gemüsebrühe", 10], ["Apfelessig", 10], ["Räuchertofu", 150]],
    ["Gemüse und Kartoffeln würfeln und kurz anschwitzen.", "Linsen und 1 Liter Brühe dazugeben, 30 Minuten köcheln.", "Räuchertofu würfeln, anbraten und zum Eintopf geben.", "Mit Essig abschmecken."]),
  r("ramen-tofu", "Ramen mit Tofu und Pak Choi", "Wärmende Nudelsuppe mit Ingwer-Brühe.", "ABEND", "SUPPE", 2, 30, [],
    [["Reisnudeln", 150], ["Tofu natur", 250], ["Pak Choi", 200], ["Champignons", 150], ["Gemüsebrühe", 15], ["Sojasauce", 30], ["Ingwer", 10], ["Knoblauch", 6], ["Frühlingszwiebeln", 30], ["Sesamöl (geröstet)", 5]],
    ["Ingwer und Knoblauch im Sesamöl anschwitzen, 1 Liter Brühe und Sojasauce dazu.", "Pilze und Tofu in Scheiben 5 Minuten darin ziehen lassen, Pak Choi zum Schluss.", "Nudeln separat garen und in Schalen verteilen.", "Mit der Brühe übergießen und mit Frühlingszwiebeln servieren."]),

  // ---------- Salate ----------
  r("quinoa-mango-salat", "Quinoa-Salat mit Mango und Bohnen", "Fruchtig-frischer Salat mit Limette und Koriander.", "MITTAG", "SALAT", 2, 25, ["meal-prep"],
    [["Quinoa", 140], ["Schwarze Bohnen (Dose)", 250], ["Mango", 200], ["Paprika rot", 150], ["Limette", 30], ["Koriander", 10], ["Avocado", 100], ["Olivenöl", 10]],
    ["Quinoa kochen und abkühlen lassen.", "Mango, Paprika und Avocado würfeln.", "Alles mit Bohnen, Limettensaft, Öl und Koriander mischen."]),
  r("griechischer-salat-tofu", "Griechischer Salat mit Tofu-Feta", "Tofu, mariniert wie Feta, mit Oliven und Pita.", "MITTAG", "SALAT", 2, 20, ["proteinreich", "schnell"],
    [["Tofu natur", 300], ["Gurke", 300], ["Tomaten", 300], ["Paprika rot", 150], ["Oliven (schwarz)", 50], ["Zwiebeln", 50], ["Olivenöl", 20], ["Zitrone", 20], ["Pita-Brot", 160]],
    ["Tofu würfeln und mit Zitronensaft, Öl und Salz 10 Minuten marinieren.", "Gemüse grob schneiden.", "Mit Oliven und Tofu mischen, dazu Pita."]),

  // ---------- Sonstiges ----------
  r("ratatouille-hirse", "Ratatouille mit Hirse", "Provenzalisches Schmorgemüse mit Kichererbsen.", "ABEND", "SONSTIGES", 2, 40, ["meal-prep"],
    [["Hirse", 140], ["Aubergine", 250], ["Zucchini", 200], ["Paprika rot", 150], ["Gehackte Tomaten (Dose)", 400], ["Zwiebeln", 80], ["Knoblauch", 8], ["Olivenöl", 20], ["Kichererbsen (Dose)", 265]],
    ["Hirse in doppelter Menge Wasser 15 Minuten garen.", "Aubergine, Zucchini, Paprika und Zwiebel würfeln und im Öl anbraten.", "Knoblauch, Tomaten und Kichererbsen dazu und 20 Minuten schmoren.", "Mit Hirse servieren."]),
  r("bulgur-gemuesepfanne", "Bulgur-Gemüsepfanne", "Orientalische Pfanne mit Petersilie und Zitrone.", "MITTAG", "SONSTIGES", 2, 25, ["günstig"],
    [["Bulgur", 150], ["Kichererbsen (Dose)", 265], ["Zucchini", 200], ["Paprika rot", 150], ["Tomatenmark", 30], ["Petersilie", 15], ["Zitrone", 20], ["Olivenöl", 15], ["Kreuzkümmel", 3]],
    ["Bulgur mit 300 ml Wasser 10 Minuten quellen lassen.", "Gemüse im Öl anbraten, Tomatenmark und Kreuzkümmel mitrösten.", "Bulgur und Kichererbsen unterheben.", "Mit Zitrone und Petersilie abschmecken."]),

  // ---------- Snacks ----------
  r("protein-shake-banane", "Protein-Shake mit Banane", "Schneller Shake nach dem Training.", "SNACK", "SONSTIGES", 1, 3, ["proteinreich", "schnell"],
    [["Erbsenproteinpulver", 30], ["Sojadrink", 250], ["Banane", 100]],
    ["Alle Zutaten im Mixer 30 Sekunden mixen."]),
  r("hummus-gemuesesticks", "Hummus mit Gemüsesticks", "Knackiger Snack für zwischendurch.", "SNACK", "SONSTIGES", 1, 5, ["schnell"],
    [["Hummus", 80], ["Karotten", 100], ["Gurke", 100], ["Paprika rot", 100]],
    ["Gemüse in Sticks schneiden und mit Hummus servieren."]),
  r("energy-balls-datteln", "Dattel-Energy-Balls", "Süße Kugeln aus Datteln, Hafer und Kakao.", "SNACK", "SONSTIGES", 6, 15, ["meal-prep"],
    [["Datteln", 150], ["Haferflocken", 60], ["Mandelmus", 40], ["Kakaopulver", 15], ["Kokosraspeln", 15]],
    ["Datteln, Haferflocken, Mandelmus und Kakao im Mixer zu einer klebrigen Masse verarbeiten.", "Zu 12 Kugeln formen und in Kokosraspeln wälzen.", "Im Kühlschrank bis zu einer Woche haltbar."]),
  r("apfel-erdnussmus", "Apfel mit Erdnussmus", "Einfach und sättigend.", "SNACK", "SONSTIGES", 1, 2, ["schnell", "günstig"],
    [["Apfel", 150], ["Erdnussmus", 25]],
    ["Apfel in Spalten schneiden und mit Erdnussmus dippen."]),
  r("proteinjoghurt-beeren", "Proteinjoghurt mit Beeren und Walnüssen", "Proteinreicher Snack aus dem Kühlschrank.", "SNACK", "SONSTIGES", 1, 3, ["proteinreich", "schnell"],
    [["Soja-Proteinjoghurt", 200], ["Beerenmix (TK)", 100], ["Walnüsse", 15]],
    ["Beeren auftauen lassen, über den Joghurt geben und mit Walnüssen bestreuen."]),
  r("edamame-snack", "Edamame mit Meersalz", "Warme Sojabohnen, ideal zum Knabbern.", "SNACK", "HUELSENFRUECHTE", 1, 8, ["proteinreich", "schnell"],
    [["Edamame (TK)", 200], ["Salz", 2]],
    ["Edamame 5 Minuten in Salzwasser kochen.", "Abgießen und mit Salz bestreuen."]),
  r("geroestete-kichererbsen", "Geröstete Paprika-Kichererbsen", "Knuspriger Knabbersnack aus dem Ofen.", "SNACK", "HUELSENFRUECHTE", 2, 35, ["günstig", "meal-prep"],
    [["Kichererbsen (Dose)", 265], ["Olivenöl", 10], ["Paprikapulver", 4], ["Salz", 2]],
    ["Kichererbsen abspülen und sehr gut trocken tupfen.", "Mit Öl, Paprika und Salz mischen.", "Bei 200 Grad 30 Minuten rösten, zwischendurch wenden."]),
  r("reiswaffeln-erdnuss-banane", "Reiswaffeln mit Erdnussmus und Banane", "Schnelle Energie vor dem Sport.", "SNACK", "SONSTIGES", 1, 3, ["schnell"],
    [["Reiswaffeln", 30], ["Erdnussmus", 20], ["Banane", 100]],
    ["Reiswaffeln mit Erdnussmus bestreichen und mit Bananenscheiben belegen."]),
  r("studentenfutter", "Studentenfutter mit Schokolade", "Nüsse, Kerne, Rosinen und dunkle Schokolade.", "SNACK", "SONSTIGES", 2, 2, ["schnell"],
    [["Mandeln", 30], ["Cashewkerne", 20], ["Rosinen", 20], ["Kürbiskerne", 15], ["Dunkle Schokolade", 15]],
    ["Schokolade grob hacken und mit allen Zutaten mischen."]),
  r("schoko-pudding-seidentofu", "Schokopudding aus Seidentofu", "Cremiger Pudding ohne Kochen.", "SNACK", "SONSTIGES", 4, 10, ["proteinreich"],
    [["Seidentofu", 400], ["Kakaopulver", 20], ["Ahornsirup", 40], ["Banane", 120]],
    ["Alle Zutaten glatt pürieren.", "In Gläser füllen und 1 Stunde kalt stellen."]),
];
